language: ruby
rvm: 2.4.1
before_script:
   - cd blog
script:
 - gem update --system
 - gem install bundler
 - bundler update --bundler
 - gem install jekyll bundler
 - JEKYLL_ENV=production bundle exec jekyll build --verbose
 - cd ..
 - ls
deploy:
   skip_cleanup: true
   provider: firebase
   token:
     secure: "1//0gozs2Gj7AaZSCgYIARAAGBASNwF-L9IrtaiRlygQn0zyhRuZotCZG8y8fS9hO-Ahu9Y3MhK3Ak85eYPeNzLtTmUItS8YYhk552o"
